### PR TITLE
fix: delete backend-config

### PR DESCRIPTION
**Pull request by lemeurherve**

### CODE REVIEW

**Review by dduportal — APPROVED** [review]
:D

**Comment by lemeurherve** [comment]
I've got this error which I don't know how to fix:
```
Commit message: "fix: delete backend-config"
 > git --version # timeout=10
 > git --version # 'git version 2.32.0'
fatal: bad object 9112228b3a31949c7fa47cc588ed5bd1d87a8ea0
```
Any idea?

**Comment by dduportal** [comment]
> I've got this error which I don't know how to fix:
> 
> ```
> Commit message: "fix: delete backend-config"
>  > git --version # timeout=10
>  > git --version # 'git version 2.32.0'
> fatal: bad object 9112228b3a31949c7fa47cc588ed5bd1d87a8ea0
> ```
> 
> Any idea?

If you browse to the classic UI of Jenkins, for the build that errored with this message (https://infra.ci.jenkins.io/job/Terraform%20Jobs/job/digitalocean/job/PR-2/1/) you can see that this revision is related to the pipeline-library. I guess that the library is still configured on infra.ci to have its changelog included on the builds (we fixed that a few days ago on trusted + ci.j).

Since it was the 1st build of this PR, then it failed to retrieve the correct changes. I see that @timja did what I would have recommended: rebuilding (short term fix): https://infra.ci.jenkins.io/blue/organizations/jenkins/Terraform%20Jobs%2Fdigitalocean/detail/PR-2/2/pipeline


=> The job fails at the lint step: you must `terraform fmt -recursive` otherwise the `make lint` step fails :)

**Review by timja — APPROVED** [review]

**Comment by dduportal** [comment]
Not really a good idea to merge PR that fail the build on a newborn project 😅

The build was failing with the following errors:

- The `make plan` step (for the production terraform) fails which indicates an error on the production terraform
- The tests are failing also...

**Comment by lemeurherve** [comment]
> Not really a good idea to merge PR that fail the build on a newborn project 😅
>
Yeah.. Wasn't sure it was due to a diff between my branch and main...

> The build was failing with the following errors:
> 
> * The `make plan` step (for the production terraform) fails which indicates an error on the production terraform

I didn't figured out why the backend-config contains {PROD...} instead of the actual content of this var

> * The tests are failing also...

That too I didn't understood, same file and folder as aws, I must miss something

**Comment by dduportal** [comment]
> Yeah.. Wasn't sure it was due to a diff between my branch and main...

Merging to principal branch is not the safer way to solve it, in particular with infra as code 😅
Don't hesitate to ask for help next time, most of the time it's an information that you did not have (e.g. an issue in knowledge sharing from my side :))

> That too I didn't understood, same file and folder as aws, I must miss something

I did not had enough time to cover the testing framework, no worries.
But to summarize, it (terratest, the testing framework) executes a terraform plan, which is failing (ref. the `make plan` failing).

> I didn't figured out why the backend-config contains {PROD...} instead of the actual content of this var

Me neither at first sight. Sounds like the secret from SOPS is not injected properly into the Jenkins credential.

**Comment by lemeurherve** [comment]
> Merging to principal branch is not the safer way to solve it, in particular with infra as code 😅 

I agree, in that case I figured there weren't anything to break yet, and wanted to try out even if you weren't available, didn't wanted to bother.

**Comment by dduportal** [comment]
> Me neither at first sight. Sounds like the secret from SOPS is not injected properly into the Jenkins credential.

Could you try to remove the credential from the UI of infra.ci, and then let the kube. management job to run again?

**Comment by dduportal** [comment]
> > Merging to principal branch is not the safer way to solve it, in particular with infra as code 😅
> 
> I agree, in that case I figured there weren't anything to break yet, and wanted to try out even if you weren't available, didn't wanted to bother.

No worry, never gonna let you down ;)

**Pull request merged**
